language: ruby
rvm:
- 2.4.0
deploy:
  skip_cleanup: true
  edge: true
  provider: chef-supermarket
  user_id: criteo
  cookbook_category: Process Management
  client_key: ".travis/client.pem"
  on:
    tags: true
    branch: master
before_deploy:
- openssl aes-256-cbc -K $encrypted_7a37245e4386_key -iv $encrypted_7a37245e4386_iv
  -in .travis/client.pem.enc -out .travis/client.pem -d
before_install:
- 'if [ -n "$encrypted_5b96b54c695c_iv" ]; then openssl aes-256-cbc -K $encrypted_5b96b54c695c_key
  -iv $encrypted_5b96b54c695c_iv -in .travis/travis-ci.pem.enc -out ~/.ssh/id_rsa
  -d ; fi'
env:
  global:
  - secure: GRVhcV8ERegECusJm4+kBSN+Ir9+xlkCLpHQVG3WUrAP5MBzI2hbu48WBje4pUABJ2JJUV5eVTE3CJiSgpscybplcHT82QWPRPwTZeQlVEEd/ocSWiE0j1ddxGbka/rie4O1CfZPjkg/XDR+GLvhtbUMSKiUw0mGG4LACsZ5b2M=
  - secure: WyeAqBAFI+ryTaDDv5Y8r/If3vXIpI7ZEWd3hg4qeG1xzyF3Ta6owuTt+P5pLbBsOUuHdT48pSAf5DHcKvYZUqUGAOX+rP4QwL+eFGOgYUbzm7gaWGpsrRJQv9ufyyLAtJnveL3a+svQydOYQ7wiBLiJzxFg7sBXTjCcDk/ldF0=
  - secure: FuS0CpFENThNP5Vu6/k9z3EWrcboCgui7M89MZJE1nxPEnOQAcPYdC4ulpF3LtguBVi10/EuCfAwqffGWXR0JdbxMJnAJpdZYh1UNbB2xp4lLi4R2MJg1NF5Ks7mgcTmisOV8iTZrn7oo8XWOeO/dvFUOMcQCghFkpHcyWwyhr0=
  - secure: MdEKOeapYvBo2bxbWYJNX2qFYixkVWC9Tr39CDxnVSE3RI7AQfC5FYkuFB2T5EdpxGtZaPPEfWmAiDW5QGR6O+oMPtIpXP/CMnqCGVwGL+qufoWYarZ/CIz9GomESrYLIb4QNUdQ1yWb+TZARDfEOchrhC2o+HjKidNmPHYHWsw=
